# Generated by Django 3.2.5 on 2021-09-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210714_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaterial',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(related_name='products', to='shop.ProductMaterial'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
